import Head from "next/head";
import Button from "../components/atoms/Button";

import Navbar from "../components/organisms/Navbar";
import Datatable from "../components/organisms/Datatable";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend test jasa marga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar active={2} />
        <Datatable />
      </main>
    </>
  );
}

interface GetServerSideProps {
  req: {
    cookies: {
      token: string;
    };
  };
}

export async function getServerSideProps({ req }: GetServerSideProps) {
  const { token } = req.cookies;

  if (!token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
